### ISSUE TITLE
Create library page component

### ISSUE THREAD

**Issue by bsuro10** [PolaDinitz/BookShare#19]
![image](https://user-images.githubusercontent.com/36992518/159739977-433c04f8-3fa2-450f-a25e-8889d116e69a.png)

Mock the data

**Comment by MaayanMordehai** [comment]
![git1](https://user-images.githubusercontent.com/25295879/160233329-05955462-04ae-401d-941b-3ec65d020a28.png)
![git2](https://user-images.githubusercontent.com/25295879/160233335-d7803e47-2a31-4a58-8b5c-ba86d1ec00f9.png)
